#!/usr/bin/python
import cv2
import rospy
from std_msgs.msg import String
import numpy as np
import time
from scipy.stats import itemfreq

def get_dominant_color(image, n_colors):
    pixels = np.float32(image).reshape((-1, 3))
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 200, .1)
    flags = cv2.KMEANS_RANDOM_CENTERS
    flags, labels, centroids = cv2.kmeans(
        pixels, n_colors, None, criteria, 10, flags)
    palette = np.uint8(centroids)
    return palette[np.argmax(itemfreq(labels)[:, -1])]


clicked = False
def onMouse(event, x, y, flags, param):
    global clicked
    if event == cv2.EVENT_LBUTTONUP:
        clicked = True


cameraCapture = cv2.VideoCapture(0)
cameraCapture.set(3,320)
cameraCapture.set(4,240)
cameraCapture.set(cv2.CAP_PROP_AUTOFOCUS,0)
time.sleep(2)
cv2.namedWindow('camera')
cv2.setMouseCallback('camera', onMouse)

# Read and process frames in loop
success, frame = cameraCapture.read()

### ROS node init ####

rospy.init_node('sign_detector')
pub = rospy.Publisher('detector/sign', String, queue_size=1)
######################
msg = String()
msg.data = "null"

while success and not clicked:
    cv2.waitKey(1)
    success, frame = cameraCapture.read()


    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Then we blur the entire frame to prevent accidental false circle
    # detections
    img = cv2.medianBlur(gray, 37)
    circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT,
                              1, 50, param1=120, param2=40)
    msg.data = "N/A"
    if not circles is None:
        circles = np.uint16(np.around(circles))
        # Filter the biggest circle, we don't want far signs to be detected
        # instead of close ones.
        max_r, max_i = 0, 0
        for i in range(len(circles[:, :, 2][0])):
            if circles[:, :, 2][0][i] > 50 and circles[:, :, 2][0][i] > max_r:
                max_i = i
                max_r = circles[:, :, 2][0][i]
        x, y, r = circles[:, :, :][0][max_i]
        # This check prevents program crash when trying to index list out of
        # its range. We actually cut a square with the whole circle inside.
        if y > r and x > r:
            square = frame[y-r:y+r, x-r:x+r]

            dominant_color = get_dominant_color(square, 2)
            if dominant_color[2] > 100:
                # Stop sign is red, so we check if there is a lot of red color
                # in circle.

                print("STOP")
                msg.data = "STOP"
            elif dominant_color[0] > 80:
                # Other signs are blue.


                zone_0 = square[square.shape[0]*3//8:square.shape[0]
                                * 5//8, square.shape[1]*1//8:square.shape[1]*3//8]
                zone_0_color = get_dominant_color(zone_0, 1)

                zone_1 = square[square.shape[0]*1//8:square.shape[0]
                                * 3//8, square.shape[1]*3//8:square.shape[1]*5//8]
                zone_1_color = get_dominant_color(zone_1, 1)

                zone_2 = square[square.shape[0]*3//8:square.shape[0]
                                * 5//8, square.shape[1]*5//8:square.shape[1]*7//8]
                zone_2_color = get_dominant_color(zone_2, 1)

                if zone_1_color[2] < 60:
                    if sum(zone_0_color) > sum(zone_2_color):
                        msg.data="LEFT"
                        print("LEFT")
                    else:
                        msg.data="RIGHT"
                        print("RIGHT")
                else:
                    if sum(zone_1_color) > sum(zone_0_color) and sum(zone_1_color) > sum(zone_2_color):
                        msg.data="FORWARD"
                        print("FORWARD")
                    elif sum(zone_0_color) > sum(zone_2_color):
                        msg.data="FORWARD AND LEFT"
                        print("FORWARD AND LEFT")
                    else:
                        msg.data="FORWARD AND RIGHT"
                        print("FORWARD AND RIGHT")
            else:
                msg.data = "N/A"
                print("N/A")

        for i in circles[0, :]:
            cv2.circle(frame, (i[0], i[1]), i[2], (0, 255, 0), 2)
            cv2.circle(frame, (i[0], i[1]), 2, (0, 0, 255), 3)

    pub.publish(msg)
    cv2.imshow('camera', frame)



cv2.destroyAllWindows()
cameraCapture.release()
