max_covariance: 0.2
finish: 6

node0:
    x: 8.0
    y: 8.0

node1:
    x: 8.4
    y: 8.05

node2:
    x: 10.3
    y: 8.15

node3:
    x: 10.6
    y: 8.15

node4:
    x: 11.3
    y: 9.2

node5:
    x: 11.3
    y: 10

node6:
    x: 11.3
    y: 15

link0_1:
    enabled: 1

link1_2:
    enabled: 1
    left: 0.6

link2_3:
    enabled: 1

link3_4:
    enabled: 1

link4_5:
    enabled: 1

link5_6:
    enabled: 1
    right: 1.0
