max_covariance: 0.2
finish: 7

node0:
    x: 8.2
    y: 8.15

node1:
    x: 10
    y: 8.1

node2:
    x: 10.5
    y: 8.1

link0_1:
    enabled: 1
    orient: 90
    orient_y: 8.6
    orient_k: -1
    orient_a: -0.2
    orient_d: 0.6
    marker_a: 45

link1_2:
    enabled: 1
    marker_a: 90
