max_covariance: 0.2
finish: 55

node0:
    x: 16.6
    y: 17

node1:
    x: 16.6
    y: 12

node2:
    x: 16
    y: 11.4

node3:
    x: 14
    y: 11.4

node4:
    x: 13.4
    y: 12

node5:
    x: 13.4
    y: 16

node6:
    x: 12
    y: 17.4

node7:
    x: 10
    y: 17.4

node8:
    x: 9
    y: 16

node9:
    x: 8
    y: 15

node10:
    x: 16.6
    y: 10

node11:
    x: 16.6
    y: 6

node12:
    x: 16
    y: 5.4

node13:
    x: 14
    y: 5.4

node14:
    x: 13.4
    y: 6

node15:
    x: 13.4
    y: 10

node16:
    x: 14
    y: 10.6

node17:
    x: 16
    y: 10.6

node18:
    x: 12
    y: 11.4

node19:
    x: 10
    y: 11.4

node20:
    x: 9.4
    y: 14

node21:
    x: 8.6
    y: 10

node22:
    x: 8
    y: 9.4

node23:
    x: 6
    y: 9.4

node24:
    x: 4.6
    y: 8

node25:
    x: 4.6
    y: 6

node26:
    x: 6
    y: 4.6

node27:
    x: 8
    y: 4.6

node28:
    x: 10
    y: 4.6

node29:
    x: 12
    y: 4.6

node30:
    x: 9.4
    y: 6

node31:
    x: 9.4
    y: 8

node32:
    x: 9.4
    y: 10

node33:
    x: 10
    y: 10.6

node34:
    x: 12
    y: 10.6

node35:
    x: 12.6
    y: 10

node36:
    x: 12.6
    y: 6

node37:
    x: 12
    y: 5.4

node38:
    x: 10
    y: 5.4

node39:
    x: 8
    y: 5.4

node40:
    x: 6
    y: 5.4

node41:
    x: 5.4
    y: 6

node42:
    x: 5.4
    y: 8

node43:
    x: 6
    y: 8.6

node44:
    x: 8
    y: 8.6

node45:
    x: 8.6
    y: 8

node46:
    x: 8.6
    y: 6

node47:
    x: 14
    y: 4.6

node48:
    x: 16
    y: 4.6

node49:
    x: 4
    y: 15

node50:
    x: 17.4
    y: 6

node51:
    x: 17.4
    y: 10

node52:
    x: 2
    y: 14

node53:
    x: 2
    y: 3.6

node54:
    x: 4
    y: 1.6

node55:
    x: 17
    y: 1.6

node56:
    x: 9.4
    y: 12

link0_1:
  enabled: 1

link1_2:
  enabled: 1
  edge_f: 260
  edge_t: 280
  edge_d: 0.7

link2_3:
  enabled: 1

link3_4:
  enabled: 1

link5_6:
  enabled: 1

link6_7:
  enabled: 1

link7_8:
  enabled: 1

link8_9:
  enabled: 1

link56_20:
  enabled: 1

link20_9:
  enabled: 1

link19_56:
  enabled: 1

link32_56:
  enabled: 1

link1_10:
  enabled: 1

link10_11:
  enabled: 1

link11_12:
  enabled: 1

link12_13:
  enabled: 1

link13_14:
  enabled: 1

link14_15:
  enabled: 1

link15_16:
  enabled: 1

link16_17:
  enabled: 1

link17_10:
  enabled: 1

link15_4:
  enabled: 1

link15_18:
  enabled: 1

link18_19:
  enabled: 1

link19_21:
  enabled: 1

link21_22:
  enabled: 1

link22_23:
  enabled: 1

link23_24:
  enabled: 1

link24_25:
  enabled: 1

link25_26:
  enabled: 1

link26_27:
  enabled: 1

link27_28:
  enabled: 1

link28_29:
  enabled: 1

link29_47:
  enabled: 1

link47_48:
  enabled: 1

link48_50:
  enabled: 1

link50_51:
  enabled: 1

link51_2:
  enabled: 1

link29_14:
  enabled: 1

link27_30:
  enabled: 1

link30_31:
  enabled: 1

link31_32:
  enabled: 1

link31_22:
  enabled: 1

link32_33:
  enabled: 1

link33_34:
  enabled: 1

link34_35:
  enabled: 1

link35_36:
  enabled: 1

link36_37:
  enabled: 1

link3_18:
  enabled: 1

link3_35:
  enabled: 1

link9_49:
  enabled: 1

link49_52:
  enabled: 1

link52_53:
  enabled: 1

link53_54:
  enabled: 1

link54_55:
  enabled: 1

link4_5:
  enabled: 1

link44_32:
  enabled: 1

link36_47:
  enabled: 1

link37_38:
  enabled: 1

link38_30:
  enabled: 1

link38_39:
  enabled: 1

link39_40:
  enabled: 1

link40_41:
  enabled: 1

link41_42:
  enabled: 1

link42_43:
  enabled: 1

link43_44:
  enabled: 1

link44_45:
  enabled: 1

link45_46:
  enabled: 1

link46_28:
  enabled: 1

link34_4:
  enabled: 1

link34_16:
  enabled: 1
