max_covariance: 0.2
finish: 2

node0:
    x: 7.8
    y: 8.1

node1:
    x: 8.4
    y: 8.1

node2:
    x: 9.8
    y: 8.15

node3:
    x: 10.6
    y: 8.15

node4:
    x: 11.3
    y: 9.0

node5:
    x: 11.3
    y: 9.2

node6:
    x: 11.3
    y: 12

node7:
    x: 11.3
    y: 15

link0_1:
    enabled: 1

link1_2:
    enabled: 1
    orient: 90
    orient_y: 8.6
    orient_k: -1
    orient_a: -0.2
    dist: 0.45

link2_3:
    enabled: 1

link3_4:
    enabled: 1

link4_5:
    enabled: 1
    orient: 90
    orient_x: 10.5
    orient_k: 1
    orient_a: 1.57
    dist: 0.8

link5_6:
    enabled: 1
    orient: 90
    orient_x: 10.5
    orient_k: 1
    orient_a: 1.57
    dist: 0.8

link6_7:
    enabled: 1
    orient: 270
    orient_x: 12.1
    orient_k: -1
    orient_a: 1.57
    dist: 0.8
